version: '3.4'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    ports:
      - "3306:3307"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: user_login
  frontback:
    image: projetofinal
    ports:
      - "8080:8080"
    #    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/user_login
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - mysql