version: '3.4'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    ports:
      - "3306:3307"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: Lisbon$2021
      MYSQL_DATABASE: user_login
